# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ocsight < Formula
  desc "OpenCode observability platform"
  homepage "https://ocsight.dev"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/heyhuynhgiabuu/ocsight/releases/download/#{version}/ocsight-darwin-x64.zip"
      sha256 "placeholder_sha256_darwin_amd64"

      def install
        bin.install "ocsight-macos-x64" => "ocsight"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/heyhuynhgiabuu/ocsight/releases/download/#{version}/ocsight-darwin-arm64.zip"
      sha256 "placeholder_sha256_darwin_arm64"

      def install
        bin.install "ocsight-macos-arm64" => "ocsight"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/heyhuynhgiabuu/ocsight/releases/download/#{version}/ocsight-linux-x64.zip"
      sha256 "placeholder_sha256_linux_amd64"
      def install
        bin.install "ocsight-linux-x64" => "ocsight"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/heyhuynhgiabuu/ocsight/releases/download/#{version}/ocsight-linux-arm64.zip"
      sha256 "placeholder_sha256_linux_arm64"
      def install
        bin.install "ocsight-linux-arm64" => "ocsight"
      end
    end
  end

  depends_on "node"
end