# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ocsight < Formula
  desc "OpenCode observability platform"
  homepage "https://ocsight.dev"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/heyhuynhgiabuu/ocsight/releases/download/#{version}/ocsight-darwin-x64.zip"
      sha256 "e948ef01f0ef35d91deec3c7dda25852f1cafd1a0018574b8034852ce6d0cc5f"

      def install
        bin.install "ocsight-macos-x64" => "ocsight"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/heyhuynhgiabuu/ocsight/releases/download/#{version}/ocsight-darwin-arm64.zip"
      sha256 "9342c672e4a668c483f0a7aa267fd7b8d7b612e3e73d5d1c2e762c895ee949dd"

      def install
        bin.install "ocsight-macos-arm64" => "ocsight"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/heyhuynhgiabuu/ocsight/releases/download/#{version}/ocsight-linux-x64.zip"
      sha256 "bbcb040eee36c07e0ca60494b355db5376b0db3f6619170bb51431dc514befa9"
      def install
        bin.install "ocsight-linux-x64" => "ocsight"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/heyhuynhgiabuu/ocsight/releases/download/#{version}/ocsight-linux-arm64.zip"
      sha256 "1a8204d7168dd0dcd5295e8c2b92dcdf6ef0e324aabcf1fe1d7634b3a1a3fd14"
      def install
        bin.install "ocsight-linux-arm64" => "ocsight"
      end
    end
  end

  depends_on "node"
end